account/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    # url(r'^login/$', views.user_login, name="user_login"),  #自定义的登录
    url(r'^login/$', auth_views.login, name='user_login'),   #django内置的登录,user_login别名是为认前端HTML调用
    url(r'^new_login/$', auth_views.login, {"template_name": "account/login.html"}),  #不需要重定向，直接指定HTML
    # url(r'^logout/$', auth_views.logout, name="user_logout"),
    url(r'^logout/$', auth_views.logout, {"template_name": "account/logout.html"}, name='user_logout'),
    url(r'^register/$', views.register, name="user_register"),
    url(r'^password-change/$', auth_views.password_change, {"post_change_redirect":"/account/password-change-done"}, name="password_change"),
    url(r'^password-change-done/$', auth_views.password_change_done, name='password_change_done'),  #改密码完成页面
    url(r'^password-change/$', auth_views.password_change, {"post_change_redirect": "/account/password-change-done"},
        name="password_change"),
    url(r'^password-change-done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^password-reset/$', auth_views.password_reset, {"template_name": "account/password_reset_form.html",
                                                          "email_template_name": "account/password_reset_email.html",
                                                          "subject_template_name": "account/password_reset_subject.txt",
                                                          "post_reset_redirect": "/account/password-reset-done"},name="password_reset"),
    url(r'^password-reset-done/$', auth_views.password_reset_done,{"template_name": "account/password_reset_done.html"}, name="password_reset_done"),
    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.password_reset_confirm,{"template_name": "account/password_reset_confirm.html",
         "post_reset_redirect": "/account/password-reset-complete"}, name="password_reset_confirm"),
    url(r'^password-reset-complete/$', auth_views.password_reset_complete,{"template_name": "account/password_reset_complete.html"}, name="password_reset_complete"),
    url(r'^my-information/$', views.myself, name="my_information"),
    url(r'^edit-my-information/$', views.myself_edit, name="edit_my_information"),
]

app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.app_title, name="app_title"),
    url(r'(?P<article_id>\d)/$', views.app_article, name="blog_detail"),
]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('app.urls', namespace='blog', app_name='blog')),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    url(r'^pwd_reset/', include("password_reset.urls", namespace='pwd_reset')),
    # url(r'^pwd_reset/', include("password_reset.urls", namespace='pwd_reset', app_name='pwd_reset')),
]

templates/base.html
{% load staticfiles %}     {# 载入staic样式目录 #}
<!DOCTYPE html>
<html lang="zh-cn">
    <head>
        <meta http-equiv="X-UA-Compatible" content="chrome=1;IE=Edge">    {# 浏览器支持 #}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>      {# 定义可重写标题占位 #}
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">    {# 引用static/css的样式 #}
    </head>
    <body>
        {% include "header.html" %}            {# 导入头栏 #}
        <div class="container">                {# 定义网页主体 #}
            {% block content %}{% endblock %}    {# 可重写主体占位 #}
        </div>
        {% include "footer.html" %}            {# 导入页脚栏 #}
        {% block javascritp %}{% endblock %}   {# 可重写javascritp占位 #}
    </body>
</html>

templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">copy right www.helijia.com</p>
</div>

templates/header.html
{% load staticfiles %}

<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="https://www.helijia.com/"><img src="{% static '/images/login.png' %}" width="100px"></a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'blog:app_title' %}">BLOG</a></li>    {# 引用URLS.PY中的标题 #}
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
                {% if user.is_authenticated %}          {# 使用交互模式方法认证是否登录，如果登录成功 #}
                    <li>
                        <div class="dropdown" style="margin-top:8px">     {# 下拉菜单 #}
                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown">  {# 按钮 #}
                                {{ user.username }}          {# 显示用户名 #}
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">      {# 下拉菜单选项数 #}
                                <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                                <li><a href="{% url 'account:my_information' %}">个人信息</a></li>
                            </ul>
                        </div>
                    </li>
                    <li><a href="{% url 'account:user_logout' %}">Logout</a></li>                 {# 此处href留空，后续补 #}
                {% else %}
                    <li><a href="{% url 'account:user_login' %}">LOGIN</a></li>   {# 如果没有登录则跳到登录页面，此处调用的是URLS.PY中的user_login #}
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

{#以下两个JavaScript：bootstrap提供的下拉菜单功能支持文件#}
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>